trigger:
- master
stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: 'react-admin'
        command: npm install

    - task: Npm@1
      displayName: 'npm build'
      inputs:
        workingDir: 'react-admin'
        command: custom
        customCommand: npm run build
        

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'react-admin\dist'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true
